import type { Metadata } from "next";
import localFont from 'next/font/local'
import '@rainbow-me/rainbowkit/styles.css';
import "./globals.css";

import Provider from "./providers";
import Navbar from "../components/Navbar/Navbar";
import { ContributeModal } from "@/components/ContributeModal/ContributeModal"
import Footer from "../components/Footer/Footer";

const myFont = localFont({
  src: '../../public/fonts/Futura Book font.ttf',
  variable: '--font-custom',
  display: 'swap'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${myFont.variable} bg-background`}
      >
        <Provider>
          <Navbar logo="/logo.svg" />
          {children}
          <ContributeModal />

          <Footer />
        </Provider>
      </body>
    </html>
  );
}
